// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobilyaETicaret.Repository;

#nullable disable

namespace MobilyaETicaret.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240124203055_KategoriFotograflari_ekleme")]
    partial class KategoriFotograflariekleme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Adresler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AdresBasligi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("IlKodu")
                        .HasColumnType("int");

                    b.Property<int>("IlceKodu")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("PostaKodu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IlceKodu");

                    b.HasIndex("MusteriId");

                    b.ToTable("Adresler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.ErisimAlanlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("ControllerAdi")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("ViewAdi")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("ErisimAlanlari");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Fotograflar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotografAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotografAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("FotografSirasi")
                        .HasColumnType("tinyint");

                    b.Property<string>("FotografYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("Fotograflar");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Ilceler", b =>
                {
                    b.Property<int>("IlceKodu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlceKodu"));

                    b.Property<int>("IlKodu")
                        .HasColumnType("int");

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("IlceKodu");

                    b.HasIndex("IlKodu");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Iller", b =>
                {
                    b.Property<int>("IlKodu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlKodu"));

                    b.Property<string>("IlAdi")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("IlKodu");

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.KategoriFotograflari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotografAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotografAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FotografYolu")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId")
                        .IsUnique();

                    b.ToTable("KategoriFotograflari");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Kategoriler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.KrediKartBilgileri", b =>
                {
                    b.Property<int>("KartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KartId"));

                    b.Property<int>("CVC")
                        .HasColumnType("int");

                    b.Property<string>("KartSahibiAdiSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KartSeriNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SonKullanmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("KartId");

                    b.ToTable("KrediKartBilgileri");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Kullanicilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciResim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciSifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PersonelMi")
                        .HasColumnType("bit");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YetkiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YetkiId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Menuler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("ErisimAlanlariId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("MenuAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MenuSirasi")
                        .HasColumnType("int");

                    b.Property<int?>("UstMenuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ErisimAlanlariId")
                        .IsUnique();

                    b.HasIndex("UstMenuId");

                    b.ToTable("Menular");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Musteriler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("KullanicilarId")
                        .HasColumnType("int");

                    b.Property<string>("Meslek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("50");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefonu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("KullanicilarId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Odemeler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KartId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OdemeTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KartId");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Personeller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("CalistigiFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("KullanicilarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MaasOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MedeniHali")
                        .HasColumnType("bit");

                    b.Property<string>("PersonelAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonelHakkinda")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PersonelKullaniciBilgileriId")
                        .HasColumnType("int");

                    b.Property<decimal>("PersonelMaasi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PersonelSoyadi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YasadigiSehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KullanicilarId");

                    b.HasIndex("PersonelKullaniciBilgileriId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.SiparisDetay", b =>
                {
                    b.Property<int>("SiparisDetayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisDetayId"));

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.Property<int>("UrunAdet")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("SiparisDetayId");

                    b.HasIndex("SiparisId");

                    b.HasIndex("UrunId");

                    b.ToTable("SiparisDetay");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Siparisler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("OdemeId")
                        .HasColumnType("int");

                    b.Property<int>("SepetId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ToplamUrunAdet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("OdemeId")
                        .IsUnique();

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Urunler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UrunFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UrunStok")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.YetkiErisim", b =>
                {
                    b.Property<int>("ErisimAlaniId")
                        .HasColumnType("int");

                    b.Property<int>("YetkiId")
                        .HasColumnType("int");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ErisimAlaniId", "YetkiId");

                    b.HasIndex("YetkiId");

                    b.ToTable("YetkiErisim");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Yetkiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("YetkiAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Yetkiler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Yorumlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("YorumUstId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.SP_DTO.Sp_AdreslerWithMusteriDTO", b =>
                {
                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresBasligi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdresId")
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EklenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("IlAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlceAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriAdiSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("PostaKodu")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AdresMusteri");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Adresler", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Ilceler", "Ilce")
                        .WithMany("Adresler")
                        .HasForeignKey("IlceKodu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Musteriler", "Musteriler")
                        .WithMany("Adresler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilce");

                    b.Navigation("Musteriler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Fotograflar", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Urunler", "Urunler")
                        .WithMany("Fotograflar")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Ilceler", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Iller", "Iller")
                        .WithMany("Ilceler")
                        .HasForeignKey("IlKodu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iller");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.KategoriFotograflari", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Kategoriler", "Kategoriler")
                        .WithOne("KategoriFotograflari")
                        .HasForeignKey("MobilyaETicaret.Core.MobilyaETicaretDatabase.KategoriFotograflari", "KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoriler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Kullanicilar", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Yetkiler", "Yetkiler")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("YetkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yetkiler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Menuler", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.ErisimAlanlari", "ErisimAlanlari")
                        .WithOne("Menuler")
                        .HasForeignKey("MobilyaETicaret.Core.MobilyaETicaretDatabase.Menuler", "ErisimAlanlariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Menuler", "UstMenu")
                        .WithMany("AltMenu")
                        .HasForeignKey("UstMenuId");

                    b.Navigation("ErisimAlanlari");

                    b.Navigation("UstMenu");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Musteriler", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Kullanicilar", "Kullanicilar")
                        .WithMany()
                        .HasForeignKey("KullanicilarId");

                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Odemeler", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.KrediKartBilgileri", "KrediKartBilgileri")
                        .WithMany("Odemeler")
                        .HasForeignKey("KartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KrediKartBilgileri");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Personeller", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Kullanicilar", "Kullanicilar")
                        .WithMany()
                        .HasForeignKey("KullanicilarId");

                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Kullanicilar", "PersonelKullaniciBilgileri")
                        .WithMany()
                        .HasForeignKey("PersonelKullaniciBilgileriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanicilar");

                    b.Navigation("PersonelKullaniciBilgileri");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.SiparisDetay", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Siparisler", "Siparisler")
                        .WithMany("SiparisDetay")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Urunler", "Urunler")
                        .WithMany("SiparisDetay")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparisler");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Siparisler", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Kullanicilar", "Kullanicilar")
                        .WithMany("Siparisler")
                        .HasForeignKey("KullaniciId");

                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Musteriler", "Musteriler")
                        .WithMany("Siparisler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Odemeler", "Odemeler")
                        .WithOne("Siparisler")
                        .HasForeignKey("MobilyaETicaret.Core.MobilyaETicaretDatabase.Siparisler", "OdemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanicilar");

                    b.Navigation("Musteriler");

                    b.Navigation("Odemeler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Urunler", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Kategoriler", "Kategoriler")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoriler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.YetkiErisim", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.ErisimAlanlari", "ErisimAlanlari")
                        .WithMany("YetkiErisimleri")
                        .HasForeignKey("ErisimAlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Yetkiler", "Yetkiler")
                        .WithMany("YetkiErisimleri")
                        .HasForeignKey("YetkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ErisimAlanlari");

                    b.Navigation("Yetkiler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Yorumlar", b =>
                {
                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Kullanicilar", "Kullanicilar")
                        .WithMany("Yorumlar")
                        .HasForeignKey("KullaniciId");

                    b.HasOne("MobilyaETicaret.Core.MobilyaETicaretDatabase.Urunler", "Urunler")
                        .WithMany("Yorumlar")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanicilar");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.ErisimAlanlari", b =>
                {
                    b.Navigation("Menuler");

                    b.Navigation("YetkiErisimleri");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Ilceler", b =>
                {
                    b.Navigation("Adresler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Iller", b =>
                {
                    b.Navigation("Ilceler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Kategoriler", b =>
                {
                    b.Navigation("KategoriFotograflari");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.KrediKartBilgileri", b =>
                {
                    b.Navigation("Odemeler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Kullanicilar", b =>
                {
                    b.Navigation("Siparisler");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Menuler", b =>
                {
                    b.Navigation("AltMenu");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Musteriler", b =>
                {
                    b.Navigation("Adresler");

                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Odemeler", b =>
                {
                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Siparisler", b =>
                {
                    b.Navigation("SiparisDetay");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Urunler", b =>
                {
                    b.Navigation("Fotograflar");

                    b.Navigation("SiparisDetay");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("MobilyaETicaret.Core.MobilyaETicaretDatabase.Yetkiler", b =>
                {
                    b.Navigation("Kullanicilar");

                    b.Navigation("YetkiErisimleri");
                });
#pragma warning restore 612, 618
        }
    }
}
